# Generated by Django 3.2.18 on 2023-06-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('is_enable', models.BooleanField(default=True)),
                ('is_confrimed', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('wallet_adress', models.CharField(max_length=50)),
                ('asset', models.IntegerField(default=0)),
                ('profit', models.IntegerField(default=0)),
            ],
        ),
    ]
