# Generated by Django 3.2.18 on 2023-06-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='asset',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
