# Generated by Django 3.2.18 on 2023-06-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20230627_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wallet_adress',
        ),
        migrations.AddField(
            model_name='user',
            name='private_key',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='public_address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='public_key',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
